---
name: sweater
channels:
  - conda-forge
dependencies:
  - python >=3.8
  - click >=8.0.1
  # Testing
  - black
  - isort
  - mypy
  - flake8
  - flake8-docstrings
  - pytest-cov
  # Development
  - tox
  - pre-commit
  - virtualenv
  - pip
  - twine
  - toml
  - bump2version
  - pip
